importer/config/routes.rb
Importer::Application.routes.draw do
  get "entry/search"
  
  resources :parse_exceptions
  resources :tag_matching_resolutions
  resources :tag_matching_exceptions do
    post :update, :on => :member
  end
  
  root :to => "tag_matching_exceptions#index"
  

end

importer/app/models/tag_matching_resolution.rb
class TagMatchingResolution < ActiveRecord::Base
  belongs_to :tag_matching_exception
  belongs_to :tag_matching_resolution_choice
end

importer/app/controllers/tag_matching_resolutions_controller.rb
class TagMatchingResolutionsController < ApplicationController
  # GET /tag_matching_resolutions
  # GET /tag_matching_resolutions.xml
  def index
    @tag_matching_resolutions = TagMatchingResolution.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tag_matching_resolutions }
    end
  end

  # GET /tag_matching_resolutions/1
  # GET /tag_matching_resolutions/1.xml
  def show
    @tag_matching_resolution = TagMatchingResolution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag_matching_resolution }
    end
  end

  # GET /tag_matching_resolutions/new
  # GET /tag_matching_resolutions/new.xml
  def new
    @tag_matching_resolution = TagMatchingResolution.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag_matching_resolution }
    end
  end

  # GET /tag_matching_resolutions/1/edit
  def edit
    @tag_matching_resolution = TagMatchingResolution.find(params[:id])
  end

  # POST /tag_matching_resolutions
  # POST /tag_matching_resolutions.xml
  def create
    @tag_matching_resolution = TagMatchingResolution.new(params[:tag_matching_resolution])

    respond_to do |format|
      if @tag_matching_resolution.save
        format.html { redirect_to(@tag_matching_resolution, :notice => 'Tag matching resolution was successfully created.') }
        format.xml  { render :xml => @tag_matching_resolution, :status => :created, :location => @tag_matching_resolution }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag_matching_resolution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tag_matching_resolutions/1
  # PUT /tag_matching_resolutions/1.xml
  def update
    @tag_matching_resolution = TagMatchingResolution.find(params[:id])

    respond_to do |format|
      if @tag_matching_resolution.update_attributes(params[:tag_matching_resolution])
        format.html { redirect_to(@tag_matching_resolution, :notice => 'Tag matching resolution was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag_matching_resolution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_matching_resolutions/1
  # DELETE /tag_matching_resolutions/1.xml
  def destroy
    @tag_matching_resolution = TagMatchingResolution.find(params[:id])
    @tag_matching_resolution.destroy

    respond_to do |format|
      format.html { redirect_to(tag_matching_resolutions_url) }
      format.xml  { head :ok }
    end
  end
end

importer/app/helpers/tag_matching_resolutions_helper.rb
module TagMatchingResolutionsHelper
end

importer/app/views/tag_matching_resolutions/_form.html.erb
<%= form_for(@tag_matching_resolution) do |f| %>
  <% if @tag_matching_resolution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_matching_resolution.errors.count, "error") %> prohibited this tag_matching_resolution from being saved:</h2>

      <ul>
      <% @tag_matching_resolution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_id %><br />
    <%= f.text_field :entry_id %>
  </div>
  <div class="field">
    <%= f.label :serialized_entry %><br />
    <%= f.text_area :serialized_entry %>
  </div>
  <div class="field">
    <%= f.label :resolution_type %><br />
    <%= f.text_field :resolution_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

importer/app/views/tag_matching_resolutions/edit.html.erb
<h1>Editing tag_matching_resolution</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_matching_resolution %> |
<%= link_to 'Back', tag_matching_resolutions_path %>

importer/app/views/tag_matching_resolutions/index.html.erb
<h1>Listing tag_matching_resolutions</h1>

<table>
  <tr>
    <th>Entry</th>
    <th>Serialized entry</th>
    <th>Resolution type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tag_matching_resolutions.each do |tag_matching_resolution| %>
  <tr>
    <td><%= tag_matching_resolution.entry_id %></td>
    <td><%= tag_matching_resolution.serialized_entry %></td>
    <td><%= tag_matching_resolution.resolution_type %></td>
    <td><%= link_to 'Show', tag_matching_resolution %></td>
    <td><%= link_to 'Edit', edit_tag_matching_resolution_path(tag_matching_resolution) %></td>
    <td><%= link_to 'Destroy', tag_matching_resolution, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag matching resolution', new_tag_matching_resolution_path %>

importer/app/views/tag_matching_resolutions/new.html.erb
<h1>New tag_matching_resolution</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_matching_resolutions_path %>

importer/app/views/tag_matching_resolutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entry:</b>
  <%= @tag_matching_resolution.entry_id %>
</p>

<p>
  <b>Serialized entry:</b>
  <%= @tag_matching_resolution.serialized_entry %>
</p>

<p>
  <b>Resolution type:</b>
  <%= @tag_matching_resolution.resolution_type %>
</p>


<%= link_to 'Edit', edit_tag_matching_resolution_path(@tag_matching_resolution) %> |
<%= link_to 'Back', tag_matching_resolutions_path %>