importer/config/routes.rb
Importer::Application.routes.draw do
  get "entry/search"
  
  resources :parse_exceptions
  resources :tag_matching_resolutions
  resources :tag_matching_exceptions do
    post :update, :on => :member
  end
  
  root :to => "tag_matching_exceptions#index"
  

end

importer/app/models/parse_exception.rb
class ParseException < ActiveRecord::Base

  def self.all_unresolved
    where("resolution_string IS NULL")
  end

end

importer/app/controllers/parse_exceptions_controller.rb
class ParseExceptionsController < ApplicationController
  # GET /parse_exceptions
  # GET /parse_exceptions.xml
  def index
    @parse_exceptions = ParseException.all_unresolved

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parse_exceptions }
    end
  end

  # GET /parse_exceptions/1
  # GET /parse_exceptions/1.xml
  def show
    @parse_exception = ParseException.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @parse_exception }
    end
  end

  # GET /parse_exceptions/new
  # GET /parse_exceptions/new.xml
  def new
    @parse_exception = ParseException.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @parse_exception }
    end
  end

  # GET /parse_exceptions/1/edit
  def edit
    @parse_exception = ParseException.find(params[:id])
  end

  # POST /parse_exceptions
  # POST /parse_exceptions.xml
  def create
    @parse_exception = ParseException.new(params[:parse_exception])

    respond_to do |format|
      if @parse_exception.save
        format.html { redirect_to(@parse_exception, :notice => 'Parse exception was successfully created.') }
        format.xml  { render :xml => @parse_exception, :status => :created, :location => @parse_exception }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @parse_exception.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parse_exceptions/1
  # PUT /parse_exceptions/1.xml
  def update
    @parse_exception = ParseException.find(params[:id])

    respond_to do |format|
      if @parse_exception.update_attributes(params[:parse_exception])
        format.html { redirect_to(@parse_exception, :notice => 'Parse exception was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @parse_exception.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parse_exceptions/1
  # DELETE /parse_exceptions/1.xml
  def destroy
    @parse_exception = ParseException.find(params[:id])
    @parse_exception.destroy

    respond_to do |format|
      format.html { redirect_to(parse_exceptions_url) }
      format.xml  { head :ok }
    end
  end
end

importer/app/helpers/parse_exceptions_helper.rb
module ParseExceptionsHelper
end

importer/app/views/parse_exceptions/_form.html.erb
<%= form_for(@parse_exception) do |f| %>
  <% if @parse_exception.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parse_exception.errors.count, "error") %> prohibited this parse_exception from being saved:</h2>

      <ul>
      <% @parse_exception.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exception_type %><br />
    <%= @parse_exception.exception_type %>
  </div>
  <div class="field">
    <%= f.label :input_string %><br />
    <%= f.text_field :input_string %>
  </div>
  <div class="field">
    <%= f.label :resolution_string %><br />
    <%= f.text_field :resolution_string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

importer/app/views/parse_exceptions/edit.html.erb
<h1>Edit Exception Resolution String</h1>

<%= render 'form' %>

<%= link_to 'Back', parse_exceptions_path %>

importer/app/views/parse_exceptions/index.html.erb
<h1>Parsing Exceptions</h1>

<table>
  <tr>
    <th>Exception</th>
    <th>Input String</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parse_exceptions.each do |parse_exception| %>
  <tr>
    <td><%= parse_exception.exception_type %></td>
    <td><%= parse_exception.input_string %></td>
    <td><%= link_to 'Resolve', edit_parse_exception_path(parse_exception) %></td>
    <td><%= link_to 'Destroy', parse_exception, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />

importer/app/views/parse_exceptions/new.html.erb
<h1>New parse_exception</h1>

<%= render 'form' %>

<%= link_to 'Back', parse_exceptions_path %>

importer/app/views/parse_exceptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Input string:</b>
  <%= @parse_exception.input_string %>
</p>

<p>
  <b>Exception type:</b>
  <%= @parse_exception.exception_type %>
</p>

<p>
  <b>Resolution string:</b>
  <%= @parse_exception.resolution_string %>
</p>


<%= link_to 'Edit', edit_parse_exception_path(@parse_exception) %> |
<%= link_to 'Back', parse_exceptions_path %>