importer/config/routes.rb
Importer::Application.routes.draw do
  get "entry/search"
  
  resources :parse_exceptions
  resources :tag_matching_resolutions
  resources :tag_matching_exceptions do
    post :update, :on => :member
  end
  
  root :to => "tag_matching_exceptions#index"
  

end

importer/app/models/tag_matching_exception.rb
class TagMatchingException < ActiveRecord::Base
  has_many :tag_matching_resolution_choices
  
  def self.all_unmatched
    where("resolved_entry_id IS NULL AND should_ignore = 0")
  end
  
  def self.all_unmatched_and_has_options
    records = []
    self.all_unmatched.each do |exc|
      records << exc if (exc.tag_matching_resolution_choices.count > 0)
    end
    records
  end
  
  def self.all_unmatched_and_no_options
    records = []
    self.all_unmatched.each do |exc|
      records << exc if (exc.tag_matching_resolution_choices.count == 0)
    end
    records
  end
end

importer/app/controllers/tag_matching_exceptions_controller.rb
class TagMatchingExceptionsController < ApplicationController
  # GET /tag_matching_exceptions
  # GET /tag_matching_exceptions.xml
  def index
    if params[:has_matches] == "true"
      @tag_matching_exceptions = TagMatchingException.all_unmatched_and_has_options
      @has_matches = true
    else
      @tag_matching_exceptions = TagMatchingException.all_unmatched_and_no_options
      @has_matches = false
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tag_matching_exceptions }
    end
  end
  
  # GET /tag_matching_exceptions/1
  # GET /tag_matching_exceptions/1.xml
  def show
    @tag_matching_exception = TagMatchingException.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag_matching_exception }
    end
  end
  
  def update_all
    
  end

  # GET /tag_matching_exceptions/new
  # GET /tag_matching_exceptions/new.xml
  def new
    @tag_matching_exception = TagMatchingException.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag_matching_exception }
    end
  end

  # GET /tag_matching_exceptions/1/edit
  def edit
    @tag_matching_exception = TagMatchingException.find(params[:id])
  end

  # POST /tag_matching_exceptions
  # POST /tag_matching_exceptions.xml
  def create
    @tag_matching_exception = TagMatchingException.new(params[:tag_matching_exception])

    respond_to do |format|
      if @tag_matching_exception.save
        format.html { redirect_to(@tag_matching_exception, :notice => 'Tag matching exception was successfully created.') }
        format.xml  { render :xml => @tag_matching_exception, :status => :created, :location => @tag_matching_exception }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag_matching_exception.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /tag_matching_exceptions/1
  # PUT /tag_matching_exceptions/1.xml
  def update
    @tag_matching_exception = TagMatchingException.find(params[:id])

    respond_to do |format|
      if @tag_matching_exception.update_attributes(params[:tag_matching_exception])
        format.html { redirect_to(:action => :index) }
#        format.html { redirect_to(@tag_matching_exception, :notice => 'Tag matching exception was successfully updated.') }
        format.xml  { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag_matching_exception.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /tag_matching_exceptions/1
  # DELETE /tag_matching_exceptions/1.xml
  def destroy
    @tag_matching_exception = TagMatchingException.find(params[:id])
#    @tag_matching_exception.destroy
    @tag_matching_exception.should_ignore = 1
    if @tag_matching_exception.save
      respond_to do |format|
        format.js
        format.html { redirect_to(tag_matching_exceptions_url) }
        format.xml  { head :ok }
      end
    end
  end
end

importer/app/helpers/tag_matching_exceptions_helper.rb
module TagMatchingExceptionsHelper
end

importer/app/views/tag_matching_exceptions/_form.html.erb
<%= form_for(@tag_matching_exception) do |f| %>
  <% if @tag_matching_exception.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_matching_exception.errors.count, "error") %> prohibited this tag_matching_exception from being saved:</h2>

      <ul>
      <% @tag_matching_exception.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_id %><br />
    <%= f.text_field :entry_id %>
  </div>
  <div class="field">
    <%= f.label :human_readable %><br />
    <%= f.text_field :human_readable %>
  </div>
  <div class="field">
    <%= f.label :serialized_entry %><br />
    <%= f.text_area :serialized_entry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

importer/app/views/tag_matching_exceptions/destroy.js.erb
$("#exception_row_<%= @tag_matching_exception.id %>").remove()

importer/app/views/tag_matching_exceptions/edit.html.erb
<h1>Editing tag_matching_exception</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_matching_exception %> |
<%= link_to 'Back', tag_matching_exceptions_path %>

importer/app/views/tag_matching_exceptions/index.html.erb
<% javascript_include_tag 'default' %>
<% csrf_meta_tag %>
<h1>Orphan Tag Entries - (<%= @tag_matching_exceptions.count %>)</h1>
<h3><%= link_to "Entries Without Matches", tag_matching_exceptions_path(:has_matches => false) %> | <%= link_to "Entries With Matches", tag_matching_exceptions_path(:has_matches => true) %></h3>
<table>
  <tr>
    <th>Unmatched Entry</th>
    <th>Choices</th>
    <th></th>
    <th></th>
  </tr>

<% @tag_matching_exceptions.each do |tag_matching_exception| %>
    <tr id='exception_row_<%= tag_matching_exception.id %>'>
      <td><%= tag_matching_exception.human_readable %></td>


      <% if @has_matches %>
        <!-- THIS SECTION IS FOR MATCHING HEADWORDS WHEN UNSURE -->
        <%= form_for tag_matching_exception, :remote => true do |f| %>
          <td>
          <%=
            include_blank = (tag_matching_exception.tag_matching_resolution_choices.count > 1)
            select("tag_matching_exception","resolved_entry_id",tag_matching_exception.tag_matching_resolution_choices.collect { |p| [p.entry.human_readable, p.entry.id] }, {:include_blank => include_blank})
          %>
          </td>
          <td><div id="match_btn_<%= tag_matching_exception.id %>"><%= f.submit "Match" %></div></td>
        <% end %>
      <% end %>


      <% if @has_matches == false %>
        <!-- THIS SECTION IS FOR LOOKING UP NEW HEADWORDS -->
        <td>
          <%= form_for tag_matching_exception, :remote => true do |f| %>
            <!-- We put a hidden tag here with this form so that our match button has a value to update from, match button starts hidden -->
            <%= hidden_field("tag_matching_exception","resolved_entry_id", :id => "tag_matching_exception_#{tag_matching_exception.id}") %>
            <div id="search_results_<%= tag_matching_exception.id %>"></div>
            <div id="match_btn_<%= tag_matching_exception.id %>" style="display: none;"><%= f.submit "Match" %></div>
          <% end %>
        </td>
        <td>
          <%= form_tag "/entry/search", :remote => true, :method => :get do %>
            <%= text_field_tag 'query', nil, :size => 10 %>
            <%= hidden_field_tag('exc_id', tag_matching_exception.id) %>
            <%= submit_tag "Search" %>
          <% end %>
        </td>
      <% end %>


      <td><%= link_to 'Ignore', tag_matching_exception, {:confirm => 'Are you sure?', :method => :delete, :remote => true} %></td>
    </tr>
<% end %>
</table>
<br />

importer/app/views/tag_matching_exceptions/new.html.erb
<h1>New tag_matching_exception</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_matching_exceptions_path %>

importer/app/views/tag_matching_exceptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entry:</b>
  <%= @tag_matching_exception.entry_id %>
</p>

<p>
  <b>Human readable:</b>
  <%= @tag_matching_exception.human_readable %>
</p>

<p>
  <b>Serialized entry:</b>
  <%= @tag_matching_exception.serialized_entry %>
</p>


<%= link_to 'Edit', edit_tag_matching_exception_path(@tag_matching_exception) %> |
<%= link_to 'Back', tag_matching_exceptions_path %>

importer/app/views/tag_matching_exceptions/update.js.erb
$("#match_btn_<%= @tag_matching_exception.id %>").html("<strong>OK</strong>")